ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)

USEFILE=$(SECTION_ROOT)/options.c

#SERVICES_ROOT=$(PRODUCT_ROOT)/../services
SERVICES_ROOT=$(PROJECT_ROOT)/../../../../services
#EXTRA_INCVPATH += $(SERVICES_ROOT)/blk/lib/include
#EXTRA_INCVPATH += $(SERVICES_ROOT)/blk
EXTRA_INCVPATH += $(SERVICES_ROOT)/usb/private/hw
#EXTRA_INCVPATH += $(PROJECT_ROOT)/include
#EXTRA_INCVPATH += $(PROJECT_ROOT)/$(SECTION)/public
#EXTRA_INCVPATH += $(PROJECT_ROOT)/../../../../services/usb/private/hw

include $(MKFILES_ROOT)/qmacros.mk

include $(SECTION_ROOT)/pinfo.mk

include $(MKFILES_ROOT)/qtargets.mk

#####AUTO-GENERATED by packaging script... do not checkin#####
   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../../../install
   USE_INSTALL_ROOT=1
##############################################################
